# Generated by Django 2.2.10 on 2020-06-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200410_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
