# Generated by Django 2.2.10 on 2020-08-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200805_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
