# Generated by Django 2.2.10 on 2020-08-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
